#!/usr/bin/env bash

alias francais="echo '/home/ia/SAMSUNG_T5/Music/Pimsleur-French/Pimsleur-French-III'"

export ETC_AUTHENTICATED_RPC_PROXY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTY0NDgxMzksImlzcyI6ImF1dGhlbnRpY2F0ZWQtcHJveHktdjEiLCJzdWIiOiJyb3RibGF1ZXJAdHdpdHRlciJ9.zfGJU2vo0lGVf0zBBdAw6MIFdL7eCijAHvq9E4_dweY
export ETC_AUTHENTICATED_RPC_PROXY_ETCLABS=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoZW50aWNhdGVkLXByb3h5LXYxIiwic3ViIjoiZXRjbGFiczFAdHdpdHRlciJ9.vTqqI1unuNLTONZy9OJlitd9zJj1EvbkseQNEygJFZA
